### ISSUE TITLE
Support non-integer values in price

### ISSUE THREAD

**Issue by kenneththomas** [kenneththomas/hive#5]
This was a pretty fat oversight.

======================================================================
ERROR: test_priceaway_reject (__main__.f2btest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hivetest.py", line 178, in test_priceaway_reject
    execreport = hive.fixgateway(fix)
  File "../pyengine/hive.py", line 14, in fixgateway
    clientorder = ordermanager(clientorder)
  File "../pyengine/hive.py", line 32, in ordermanager
    riskcheckresult = riskcheck.limitcheck(symbol,int(price),int(quantity))
**ValueError: invalid literal for int() with base 10: '30.3'**

**Comment by kenneththomas** [comment]
riskcheckresult = riskcheck.limitcheck(symbol,**float**(price),int(quantity))

**Comment by kenneththomas** [comment]
unrelated
`import socket
import hive

def Main():
    host = "127.0.0.1"
    port = awfeahwefawhefawef

    mySocket = socket.socket()
    mySocket.bind((host,port))

    mySocket.listen(1)
    conn, addr = mySocket.accept()
    print ("Connection from: " + str(addr))
    while True:
        data = conn.recv(1024).decode()
        if not data:
            break
        print ("from connected  user: " + str(data))

        #data = str(data).upper()
        data = hive.fixgateway(data)
        print ("sending: " + str(data))
        conn.send(data.encode())

    conn.close()

if __name__ == '__main__':
    Main()
`

`
import socket

def Main():
        host = '127.0.0.1'
        port = 20015

        mySocket = socket.socket()
        mySocket.connect((host,port))

        message = input(" -> ")

        while message != 'q':
                mySocket.send(str(message).encode())
                data = mySocket.recv(1024).decode()

                print ('Received from server: ' + data)

                message = input(" -> ")

        mySocket.close()

if __name__ == '__main__':
    Main()
`
